version: '3'
services:
  python:
    image: hiepph1707/${IMAGE_PYTHON}:${IMAGE_TAG}
    environment:
      - HOSTNAME=`hostname`
    container_name: python-app
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
